---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
images:
  - name: bretfisher/wordsmith-api
    newName: ghcr.io/raphael-fretter/wordsmith-api
    newTag: stable-20230719-f811195
  - name: bretfisher/wordsmith-web
    newName: ghcr.io/raphael-fretter/wordsmith-web
    newTag: stable-20230713-1d47138
configMapGenerator:
  - name: db-schema
    files:
      - words.sql
